### ISSUE TITLE
Problem retrieving data

### ISSUE THREAD

**Issue by RSO9192** [Risk-Team/CAVAanalytics#3]
The loadGridData function, which is called within the load_data of CAVAanalytics yields error messages, apparently this can happen randomly and it is not associated with any specific dataset. This is a problem with the servers and it is aggravated during parallelisation as failure of one job in one session causes the following error:

```
library(CAVAanalytics)

remote.data <- load_data(country = "Togo", variable="tasmax",
                         years.hist=1990:1992, years.proj=2050:2052,
                         path.to.data = "CORDEX-CORE", domain="AFR-22")

Error in `dplyr::mutate()`:ata (18 simulations). Using 6 sessions by default
ℹ In argument: `models = suppressWarnings(...)`.
Caused by error in `._jobjRef_dollar()`:
! no field, method or inner class called 'use_cli_format' 
Run `rlang::last_trace()` to see where the error occurred.
```

 Upon inspection, the error is, for example:
```
Jan 11, 2024 11:41:48 AM ucar.nc2.dt.grid.GeoGrid readDataSlice
SEVERE: GeoGrid.getdataSlice() on variable pr dataset dods://data.meteo.unican.es/thredds/dodsC/fao/interp025/aggregations/CORDEX/output/AFR-22/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/REMO2015/v1/day/CORDEX_output_AFR-22_GERICS_MOHC-HadGEM2-ES_rcp85_r1i1p1_REMO2015_v1_day.ncml
java.io.IOException: java.io.EOFException; pr -- 8700:9057,127:147,97:104
      at ucar.nc2.dods.DODSNetcdfFile.readData(DODSNetcdfFile.java:1665)
      at ucar.nc2.Variable.reallyRead(Variable.java:907)
      at ucar.nc2.Variable._read(Variable.java:892)
      at ucar.nc2.Variable.read(Variable.java:703)
      at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:557)
      at ucar.nc2.dataset.VariableDS._read(VariableDS.java:537)
      at ucar.nc2.SectionReader.reallyRead(SectionReader.java:61)
      at ucar.nc2.dataset.VariableDS._read(VariableDS.java:507)
      at ucar.nc2.dataset.VariableDS._read(VariableDS.java:531)
      at ucar.nc2.Variable.read(Variable.java:703)
      at ucar.nc2.Variable.read(Variable.java:649)
      at ucar.nc2.dt.grid.GeoGrid.readDataSlice(GeoGrid.java:606)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
      at RJavaTools.invokeMethod(RJavaTools.java:399)


```

**Comment by RSO9192** [comment]
The problem was solved with updates to THREDDS server version 4
